version: "3.8"
services:
  discoveryservice1:
    restart: always
    build:
      context: ./discovery-service
    environment: 
      DISCOVERY_SERVICE_HOSTNAME: discoveryservice1
      DISCOVERY_SERVICE_DEFAULT_ZONE: http://discoveryservice2:8761/eureka
    ports:
      - 8761:8761
    depends_on: 
      - database
  discoveryservice2:
    restart: always
    build:
      context: ./discovery-service
    environment: 
      DISCOVERY_SERVICE_HOSTNAME: discoveryservice2
      DISCOVERY_SERVICE_DEFAULT_ZONE: http://discoveryservice1:8761/eureka
    ports:
      - 8762:8761
    depends_on: 
      - database
  gatewayservice:
    restart: always
    build:
      context: ./gateway-service
    ports:
      - 8080:8080
    depends_on: 
      - discoveryservice1
      - discoveryservice2
      - database
  counterservice:
    restart: always
    build:
      context: ./counters-service
    environment: 
      DB_HOST: database
      DB_PORT: 3306
      DB_ROOT_PWD: ${DB_ROOT_PWD:-mysqlpwd}
    ports:
      - "8001"
    depends_on: 
      - discoveryservice1
      - discoveryservice2
      - gatewayservice
      - database
  uiservice:
    restart: always
    build:
      context: ./ui-service
    ports:
      - "8002"
    depends_on: 
      - discoveryservice1
      - discoveryservice2
      - gatewayservice
      - database
  database:
    container_name: database
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD:-mysqlpwd}
    volumes:
      - database-volume:/var/lib/mysql
volumes:
  database-volume:
    
    
