version: "3.8"
services:
  discoveryservice:
    restart: on-failure
    build:
      context: ./discovery-service
    ports:
      - "8761"
    depends_on: 
      - database
  gatewayservice:
    restart: on-failure
    build:
      context: ./gateway-service
    ports:
      - 8080:8080
    depends_on: 
      - discoveryservice
      - database
  counterservice:
    restart: on-failure
    build:
      context: ./counters-service
    environment: 
      DB_HOST: database
      DB_PORT: 3306
      DB_ROOT_PWD: ${DB_ROOT_PWD:-mysqlpwd}
      
    ports:
      - "8001"
    depends_on: 
      - discoveryservice
      - gatewayservice
      - database
  database:
    container_name: database
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD:-mysqlpwd}
    
    
